[project]
name = "cerebros"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.6"
dependencies = [
    "jsonschema>=4.25.1",
    "pyyaml>=6.0.3",
    "rich>=14.2.0",
    "textual>=0.54.0",
]
